### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by Prakash-Haldar**
Contributors Section

### CODE REVIEW

**Review by geekymeeky — CHANGES_REQUESTED** [review]
Kindly add these lines
`## ✨ Contributors  

Thanks go to these **Wonderful People** 👨🏻‍💻    🚀 **Contributions** of any kind are welcome! `

**Comment by Prakash-Haldar** [comment]
@geekymeeky Done . Please Check once

**Comment by geekymeeky** [comment]
> Kindly add these lines
> `##  Contributors
> 
> Thanks go to these **Wonderful People** 👨🏻‍💻  **Contributions** of any kind are welcome! `

@Prakash-Haldar you missed the second line. Kindly add it.

**Review by geekymeeky — APPROVED** [review]

**Comment by geekymeeky** [comment]
Fixes #2

**Pull request merged**
